name: Deploy to GitHub Releases

on:
  push:
    branches:
      - master
jobs:
  deploy-ggmanager-to-github-releases:
    runs-on: windows-latest
    steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
       
     - name: Get Version from Project File
       id: get-version
       shell: bash
       run: echo "version=$(grep -oE '<Version>[^<]+' GGManager/GGManager.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT
       
     - name: Install .NET
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 6.0.x

     - name: Publish Application
       run: dotnet publish MyProject/MyProject.csproj -c Release -o publish -r win-x64 --self-contained true

     - name: Create Velopack Release
       run: |
          dotnet tool install -g vpk
          vpk download github --repoUrl https://github.com/movsar/good-grades
          vpk pack -u GGManager -v ${{ steps.get-version.outputs.version }} -p publish
          vpk upload github --repoUrl https://github.com/movsar/good-grades --publish --releaseName "GGManager ${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }}
