name: Deploy GGManager to Remote Server via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
       
     - name: Get Manager Version from Project File
       id: get-manager-version
       shell: bash
       run: echo "version=$(grep -oE '<Version>[^<]+' GGManager/GGManager.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT
  
     - name: Install .NET
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 6.0.x

     - name: Publish GGManager
       run: dotnet publish GGManager/GGManager.csproj -c Release -o publish-manager -r win-x86 -p:PublishReadyToRun=true

     - name: Create release
       run: |
          dotnet tool install -g vpk
          vpk pack -u GGManager -v ${{ steps.get-manager-version.outputs.version }} -p publish-manager

     - name: Set up SSH agent
       uses: webfactory/ssh-agent@v0.9.0
       with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

     - name: Deploy via Rsync
       run: |
          echo "Deploying files to remote server..."
          rsync -avzr --delete \
          publish-manager/Releases/ \
          root@movsar.dev:/var/www/movsar.dev/releases/good-grades/manager/ \
          -e 'ssh -p 42022'
